/**
 * Compiles every fixture statement through Typst and writes the outcome to
 * `src/__fixtures__/TYPST_CORPUS.md`, so a regression in the converter is visible as a diff rather than
 * only as a failed assertion.
 *
 * The whole file skips when there is no Typst binary; the report on disk is left as it was.
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  markdownToTypst,
  normaliseForCmarker,
  renderPdf,
  TypstCompileError,
  typstAvailable,
} from "./index.js";
import { loadFixtures, placeholderAssets } from "./test.helpers.js";
import { pdfPages, pdfText } from "./test.pdf.js";

const REPORT = fileURLToPath(new URL("./__fixtures__/TYPST_CORPUS.md", import.meta.url));

interface Row {
  code: string;
  name: string;
  ok: boolean;
  pages: number;
  bytes: number;
  images: number;
  droppedImages: string[];
  escapedHtml: number;
  reason: string;
}

function firstError(error: unknown): string {
  if (error instanceof TypstCompileError) {
    const lines = error.stderr
      .split("\n")
      .filter((line) => line.trimStart().startsWith("error:"))
      .map((line) => line.trim());
    return lines[0] ?? error.message;
  }
  return error instanceof Error ? error.message : String(error);
}

describe.skipIf(!(await typstAvailable()))("typst corpus", () => {
  it("compiles the fixture statements and writes the report", async () => {
    const fixtures = await loadFixtures();
    const rows: Row[] = [];

    for (const fixture of fixtures) {
      const normalised = normaliseForCmarker(fixture.source);
      const source = markdownToTypst(fixture.source, fixture.meta);
      const assets = placeholderAssets(normalised.images);
      const row: Row = {
        code: fixture.code,
        name: fixture.meta.name,
        ok: false,
        pages: 0,
        bytes: 0,
        images: normalised.images.length,
        droppedImages: [...normalised.droppedImages],
        escapedHtml: normalised.escapedHtml.length,
        reason: "",
      };
      try {
        const pdf = await renderPdf(source, { assets });
        row.ok = true;
        row.bytes = pdf.length;
        row.pages = await pdfPages(pdf);
        const text = await pdfText(pdf);
        if (!text.includes(fixture.meta.name)) {
          row.ok = false;
          row.reason = "the problem name is missing from the rendered page";
        }
      } catch (error) {
        row.reason = firstError(error);
      }
      rows.push(row);
    }

    await writeFile(REPORT, renderReport(rows), "utf8");

    const failures = rows.filter((row) => !row.ok);
    expect(failures.map((row) => `${row.code}: ${row.reason}`)).toEqual([]);
  }, 900_000);
});

function renderReport(rows: readonly Row[]): string {
  const ok = rows.filter((row) => row.ok).length;
  const withImages = rows.filter((row) => row.images > 0);
  const withDropped = rows.filter((row) => row.droppedImages.length > 0);
  const withHtml = rows.filter((row) => row.escapedHtml > 0);

  const lines: string[] = [
    "# Typst corpus check",
    "",
    "Generated by `src/typst.corpus.test.ts`. Every statement under `src/__fixtures__/statements` is",
    "converted with `markdownToTypst` and compiled with the Typst binary; the check passes when",
    "the PDF compiles and the problem name appears in its text.",
    "",
    `Result: **${ok} of ${rows.length} statements compile.**`,
    "",
    "| Problem | Result | Pages | Size | Images | Dropped | Escaped HTML |",
    "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
  ];

  for (const row of rows) {
    const result = row.ok ? "ok" : `**fails** — ${row.reason}`;
    lines.push(
      `| \`${row.code}\` | ${result} | ${row.pages || "-"} | ` +
        `${row.bytes ? `${Math.round(row.bytes / 1024)} kB` : "-"} | ` +
        `${row.images || "-"} | ${row.droppedImages.length || "-"} | ${row.escapedHtml || "-"} |`,
    );
  }

  lines.push(
    "",
    "## Notes",
    "",
    "- Statement images are supplied to the compile as one-pixel placeholders. The problem",
    "  repository keeps its media outside the problem folders, and `@moj/content` is only",
    "  responsible for resolving the path; the web app passes the real bytes through",
    "  `renderPdf`'s `assets`.",
    `- ${withImages.length} statements reference a local image: ` +
      `${withImages.map((row) => `\`${row.code}\``).join(", ") || "none"}.`,
    `- ${withDropped.length} statements reference a remote image, which Typst cannot fetch and` +
      " the converter drops: " +
      `${withDropped.map((row) => `\`${row.code}\``).join(", ") || "none"}.`,
    `- ${withHtml.length} statements contain raw HTML. \`<img>\` becomes a real image; anything` +
      " else is escaped into literal text so that placeholders such as `<name>` survive: " +
      `${withHtml.map((row) => `\`${row.code}\``).join(", ") || "none"}.`,
    "",
    "## Converter fixes this check drove",
    "",
    "- Image paths are rewritten to be root-absolute and `cmarker` is handed an `image`",
    "  function defined in `statement.typ`. `cmarker` evaluates its generated Typst with the",
    "  package's own file identity, so both relative and root-absolute paths were being looked",
    "  up under `typst/packages/preview/cmarker/<version>/` instead of under the compile root.",
    "- Every maths delimiter is normalised to `$...$` / `$$...$$` before `cmarker` sees it,",
    "  because pulldown-cmark reads `~x~` as strikethrough rather than as maths.",
    "- Heading levels are normalised so the top section is `##`, and a leading `# Title` is",
    "  dropped; the canonical name comes from the problem metadata and is set by the header.",
    "- Automatic heading labels are switched off (`heading-labels: none`), otherwise a booklet",
    "  whose problems all have an `Input` section fails on duplicate labels.",
    '- `smart-punctuation` is off, so a literal `"YES"` in an output specification is not',
    "  turned into curly quotes.",
    "",
  );

  return `${lines.join("\n")}\n`;
}
