// Shared feed plumbing for the RSS, Atom, sitemap and iCalendar routes.
// Django builds these with `django.utils.feedgenerator`; this is the same
// output shape, generated by hand.

/**
 * Absolute origin for feed links. `NEXT_PUBLIC_SITE_URL` is the name the feed
 * spec uses; the compose files already set `NEXT_PUBLIC_APP_URL`, so both work.
 */
export function siteUrl(): string {
  const raw = process.env.NEXT_PUBLIC_SITE_URL ?? process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  return raw.replace(/\/+$/, "");
}

export function absolute(path: string): string {
  if (/^https?:\/\//.test(path)) return path;

  return `${siteUrl()}${path.startsWith("/") ? path : `/${path}`}`;
}

export function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** RFC 2822, the date format RSS 2.0 wants. */
export function rfc2822(time: number): string {
  return new Date(time).toUTCString().replace("GMT", "+0000");
}

/** RFC 3339, the date format Atom wants. */
export function rfc3339(time: number): string {
  return new Date(time).toISOString().replace(/\.\d{3}Z$/, "Z");
}

export type FeedEntry = {
  id: string;
  title: string;
  /** Site-relative path. */
  link: string;
  descriptionHtml: string;
  published: number;
  updated: number;
};

export type FeedMeta = {
  title: string;
  description: string;
  /** Site-relative path of the page the feed describes. */
  link: string;
  /** Site-relative path of this feed itself. */
  self: string;
};

export function renderRss(meta: FeedMeta, entries: FeedEntry[]): string {
  const built = entries.length > 0 ? Math.max(...entries.map((entry) => entry.updated)) : Date.now();

  const items = entries
    .map(
      (entry) => `    <item>
      <title>${escapeXml(entry.title)}</title>
      <link>${escapeXml(absolute(entry.link))}</link>
      <description>${escapeXml(entry.descriptionHtml)}</description>
      <guid isPermaLink="false">${escapeXml(absolute(entry.link))}</guid>
      <pubDate>${rfc2822(entry.published)}</pubDate>
    </item>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(meta.title)}</title>
    <link>${escapeXml(absolute(meta.link))}</link>
    <description>${escapeXml(meta.description)}</description>
    <atom:link href="${escapeXml(absolute(meta.self))}" rel="self"></atom:link>
    <language>en-us</language>
    <lastBuildDate>${rfc2822(built)}</lastBuildDate>
${items}
  </channel>
</rss>
`;
}

export function renderAtom(meta: FeedMeta, entries: FeedEntry[]): string {
  const updated = entries.length > 0 ? Math.max(...entries.map((entry) => entry.updated)) : Date.now();

  const items = entries
    .map(
      (entry) => `  <entry>
    <title>${escapeXml(entry.title)}</title>
    <link href="${escapeXml(absolute(entry.link))}" rel="alternate"></link>
    <published>${rfc3339(entry.published)}</published>
    <updated>${rfc3339(entry.updated)}</updated>
    <id>${escapeXml(absolute(entry.link))}</id>
    <summary type="html">${escapeXml(entry.descriptionHtml)}</summary>
  </entry>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-us">
  <title>${escapeXml(meta.title)}</title>
  <link href="${escapeXml(absolute(meta.link))}" rel="alternate"></link>
  <link href="${escapeXml(absolute(meta.self))}" rel="self"></link>
  <id>${escapeXml(absolute(meta.self))}</id>
  <updated>${rfc3339(updated)}</updated>
  <subtitle>${escapeXml(meta.description)}</subtitle>
${items}
</feed>
`;
}

export function xmlResponse(body: string, contentType: string): Response {
  return new Response(body, {
    headers: {
      "content-type": contentType,
      "cache-control": "public, max-age=300, s-maxage=300",
    },
  });
}

export const RSS_CONTENT_TYPE = "application/rss+xml; charset=utf-8";

export const ATOM_CONTENT_TYPE = "application/atom+xml; charset=utf-8";
