export type SeedLanguage = {
  key: string;
  name: string;
  shortName: string;
  commonName: string;
  editorMode: string;
  shikiLang: string;
  template: string;
  info: string;
  description: string;
  extension: string;
  /** The `pk` of the row in DMOJ's `language_all.json`, for the runtimes that are
   *  in it. Languages added since have none. */
  legacyId?: number;
};

export type SeedNavItem = {
  legacyId: number;
  order: number;
  key: string;
  label: string;
  path: string;
  regex: string;
  parentLegacyId: number | null;
};

export const SEED_LANGUAGES: SeedLanguage[] = [
  {
    key: "PY2",
    name: "Python 2",
    shortName: "",
    commonName: "Python",
    editorMode: "python",
    shikiLang: "python",
    template: "",
    info: "",
    description: "",
    extension: "py",
    legacyId: 1,
  },
  {
    key: "CPP03",
    name: "C++03",
    shortName: "C++03",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 2,
  },
  {
    key: "RUBY18",
    name: "Ruby 1.8",
    shortName: "",
    commonName: "Ruby",
    editorMode: "ruby",
    shikiLang: "ruby",
    template: "",
    info: "",
    description: "",
    extension: "rb",
    legacyId: 4,
  },
  {
    key: "PHP",
    name: "PHP",
    shortName: "",
    commonName: "PHP",
    editorMode: "php",
    shikiLang: "php",
    template: "",
    info: "",
    description: "",
    extension: "php",
    legacyId: 5,
  },
  {
    key: "PERL",
    name: "Perl",
    shortName: "",
    commonName: "Perl",
    editorMode: "perl",
    shikiLang: "perl",
    template: "",
    info: "",
    description: "",
    extension: "pl",
    legacyId: 6,
  },
  {
    key: "PY3",
    name: "Python 3",
    shortName: "",
    commonName: "Python",
    editorMode: "python",
    shikiLang: "python",
    template: "",
    info: "",
    description: "",
    extension: "py",
    legacyId: 8,
  },
  {
    key: "C",
    name: "C",
    shortName: "",
    commonName: "C",
    editorMode: "c_cpp",
    shikiLang: "c",
    template: "#include <stdio.h>\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "c",
    legacyId: 9,
  },
  {
    key: "PAS",
    name: "Pascal",
    shortName: "",
    commonName: "Pascal",
    editorMode: "pascal",
    shikiLang: "pascal",
    template: "",
    info: "",
    description: "",
    extension: "pas",
    legacyId: 10,
  },
  {
    key: "CPP11",
    name: "C++11",
    shortName: "C++11",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 13,
  },
  {
    key: "MONOCS",
    name: "C#",
    shortName: "C#",
    commonName: "C#",
    editorMode: "csharp",
    shikiLang: "csharp",
    template: "",
    info: "",
    description: "",
    extension: "cs",
    legacyId: 14,
  },
  {
    key: "HASK",
    name: "Haskell",
    shortName: "HASK",
    commonName: "Haskell",
    editorMode: "haskell",
    shikiLang: "haskell",
    template: "",
    info: "",
    description: "",
    extension: "hs",
    legacyId: 15,
  },
  {
    key: "GO",
    name: "Go",
    shortName: "GO",
    commonName: "Go",
    editorMode: "golang",
    shikiLang: "go",
    template: "",
    info: "",
    description: "",
    extension: "go",
    legacyId: 16,
  },
  {
    key: "PYPY",
    name: "PyPy 2",
    shortName: "PYPY2",
    commonName: "Python",
    editorMode: "python",
    shikiLang: "python",
    template: "",
    info: "",
    description: "",
    extension: "py",
    legacyId: 17,
  },
  {
    key: "PYPY3",
    name: "PyPy 3",
    shortName: "PYPY3",
    commonName: "Python",
    editorMode: "python",
    shikiLang: "python",
    template: "",
    info: "",
    description: "",
    extension: "py",
    legacyId: 18,
  },
  {
    key: "F95",
    name: "Fortran",
    shortName: "",
    commonName: "Fortran",
    editorMode: "fortran",
    shikiLang: "fortran",
    template: "",
    info: "",
    description: "",
    extension: "f95",
    legacyId: 19,
  },
  {
    key: "NASM",
    name: "NASM",
    shortName: "",
    commonName: "Assembly",
    editorMode: "assembly_x86",
    shikiLang: "asm",
    template: "",
    info: "",
    description: "",
    extension: "asm",
    legacyId: 20,
  },
  {
    key: "RUBY",
    name: "Ruby",
    shortName: "",
    commonName: "Ruby",
    editorMode: "ruby",
    shikiLang: "ruby",
    template: "",
    info: "",
    description: "",
    extension: "rb",
    legacyId: 21,
  },
  {
    key: "LUA",
    name: "Lua",
    shortName: "LUA",
    commonName: "Lua",
    editorMode: "lua",
    shikiLang: "lua",
    template: "",
    info: "",
    description: "",
    extension: "lua",
    legacyId: 22,
  },
  {
    key: "OCAML",
    name: "OCaml",
    shortName: "OCAML",
    commonName: "OCaml",
    editorMode: "ocaml",
    shikiLang: "ocaml",
    template: "",
    info: "",
    description: "",
    extension: "ml",
    legacyId: 23,
  },
  {
    key: "TUR",
    name: "Turing",
    shortName: "",
    commonName: "Turing",
    editorMode: "turing",
    shikiLang: "text",
    template: "",
    info: "tprologc; OpenTuring 1.0.0",
    description: "",
    extension: "t",
    legacyId: 24,
  },
  {
    key: "JAVA8",
    name: "Java 8",
    shortName: "",
    commonName: "Java",
    editorMode: "java",
    shikiLang: "java",
    template:
      "import java.io.*;\r\nimport java.util.*;\r\n\r\npublic class Main {\r\n    public static void main(String[] args) {\r\n\r\n    }\r\n}",
    info: "",
    description: "",
    extension: "java",
    legacyId: 25,
  },
  {
    key: "V8JS",
    name: "V8 JavaScript",
    shortName: "",
    commonName: "JS",
    editorMode: "javascript",
    shikiLang: "javascript",
    template:
      "/* \r\n * This is a custom version of V8 that adds six functions in order to perform I/O and aid in online judging.\r\n *\r\n * * `print(...)`: similar to Python's `print`, prints all argument separated by space followed by new line.\r\n * * `flush()`: flushes stdout, ensuring everything output by `print()` immediately shows up.\r\n * * `gets()`: similar to the Ruby equivalent, returns one line of input from `stdin`.\r\n * * `read(bytes)`: read `bytes` bytes from stdin as an `ArrayBuffer`.\r\n * * `write(buffer)`: write a typed array, `ArrayBuffer`, or a view of `ArrayBuffer` to stdout.\r\n * * `quit(code)`: exits the program with `code`.\r\n * * You can also assign to the global variable `autoflush` to control whether `print()` flushes.\r\n *\r\n */",
    info: "",
    description:
      "This is a custom version of V8 that adds six functions in order to perform I/O and aid in online judging.\r\n\r\n* `print(...)`: similar to Python's `print`, prints all argument separated by space followed by new line.\r\n* `flush()`: flushes stdout, ensuring everything output by `print()` immediately shows up.\r\n* `gets()`: similar to the Ruby equivalent, returns one line of input from `stdin`.\r\n* `read(bytes)`: read `bytes` bytes from stdin as an [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).\r\n* `write(buffer)`: write a typed array, `ArrayBuffer`, or a view of `ArrayBuffer` to stdout.\r\n* `quit(code)`: exits the program with `code`.\r\n* You can also assign to the global variable `autoflush` to control whether `print()` flushes.",
    extension: "js",
    legacyId: 27,
  },
  {
    key: "D",
    name: "D",
    shortName: "",
    commonName: "D",
    editorMode: "d",
    shikiLang: "d",
    template: "import std.stdio;\r\n\r\nvoid main() {\r\n\r\n}",
    info: "",
    description: "",
    extension: "d",
    legacyId: 29,
  },
  {
    key: "BF",
    name: "Brain****",
    shortName: "",
    commonName: "Brain****",
    editorMode: "plain_text",
    shikiLang: "text",
    template: "",
    info: "",
    description:
      "Classical [brain\\*\\*\\*\\*](http://www.muppetlabs.com/~breadbox/bf/) with as many byte-sized cells as there are bytes in the memory limit.",
    extension: "c",
    legacyId: 30,
  },
  {
    key: "OBJC",
    name: "Objective-C",
    shortName: "",
    commonName: "ObjC",
    editorMode: "objectivec",
    shikiLang: "objective-c",
    template: "",
    info: "",
    description: "Objective-C with GNUstep Base 1.22.1 on GCC 4.7.2+.",
    extension: "m",
    legacyId: 31,
  },
  {
    key: "CPP14",
    name: "C++14",
    shortName: "C++14",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 33,
  },
  {
    key: "MONOVB",
    name: "Visual Basic",
    shortName: "VB",
    commonName: "VB",
    editorMode: "vbscript",
    shikiLang: "vb",
    template: "",
    info: "",
    description: "",
    extension: "vb",
    legacyId: 34,
  },
  {
    key: "CLANG",
    name: "Clang",
    shortName: "Clang",
    commonName: "C",
    editorMode: "c_cpp",
    shikiLang: "c",
    template: "#include <stdio.h>\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "c",
    legacyId: 35,
  },
  {
    key: "CLANGX",
    name: "Clang++",
    shortName: "Clang++",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 36,
  },
  {
    key: "DART",
    name: "Dart",
    shortName: "DART",
    commonName: "Dart",
    editorMode: "dart",
    shikiLang: "dart",
    template: "",
    info: "",
    description: "",
    extension: "dart",
    legacyId: 37,
  },
  {
    key: "TCL",
    name: "TCL",
    shortName: "TCL",
    commonName: "TCL",
    editorMode: "tcl",
    shikiLang: "tcl",
    template: "",
    info: "",
    description: "",
    extension: "tcl",
    legacyId: 38,
  },
  {
    key: "CBL",
    name: "COBOL",
    shortName: "",
    commonName: "COBOL",
    editorMode: "cobol",
    shikiLang: "cobol",
    template: "",
    info: "",
    description: "",
    extension: "cbl",
    legacyId: 39,
  },
  {
    key: "MONOFS",
    name: "F#",
    shortName: "F#",
    commonName: "F#",
    editorMode: "fsharp",
    shikiLang: "fsharp",
    template: "",
    info: "",
    description: "",
    extension: "fs",
    legacyId: 40,
  },
  {
    key: "SCM",
    name: "Scheme",
    shortName: "SCM",
    commonName: "Scheme",
    editorMode: "scheme",
    shikiLang: "scheme",
    template: "",
    info: "",
    description: "",
    extension: "scm",
    legacyId: 41,
  },
  {
    key: "ADA",
    name: "Ada",
    shortName: "ADA",
    commonName: "Ada",
    editorMode: "ada",
    shikiLang: "ada",
    template: "",
    info: "",
    description: "",
    extension: "adb",
    legacyId: 42,
  },
  {
    key: "AWK",
    name: "AWK",
    shortName: "AWK",
    commonName: "Awk",
    editorMode: "AWK",
    shikiLang: "awk",
    template: "",
    info: "",
    description: "",
    extension: "awk",
    legacyId: 43,
  },
  {
    key: "RUST",
    name: "Rust",
    shortName: "RUST",
    commonName: "Rust",
    editorMode: "rust",
    shikiLang: "rust",
    template: '#[macro_use] extern crate dmoj;\r\n\r\nfn main() {\r\n    println!("Hello, World!");\r\n}',
    info: "",
    description: "",
    extension: "rs",
    legacyId: 44,
  },
  {
    key: "COFFEE",
    name: "CoffeeScript",
    shortName: "",
    commonName: "JS",
    editorMode: "coffee",
    shikiLang: "coffeescript",
    template: "",
    info: "",
    description: "",
    extension: "coffee",
    legacyId: 45,
  },
  {
    key: "PRO",
    name: "Prolog",
    shortName: "PRO",
    commonName: "Prolog",
    editorMode: "prolog",
    shikiLang: "prolog",
    template: "",
    info: "",
    description: "",
    extension: "pl",
    legacyId: 47,
  },
  {
    key: "FORTH",
    name: "Forth",
    shortName: "FORTH",
    commonName: "Forth",
    editorMode: "forth",
    shikiLang: "text",
    template: "",
    info: "",
    description: "Gforth 0.7.2.\r\n\r\nSubmissions ran as `gforth <source>.fs -e bye`.",
    extension: "fs",
    legacyId: 49,
  },
  {
    key: "ICK",
    name: "INTERCAL",
    shortName: "",
    commonName: "Intercal",
    editorMode: "text",
    shikiLang: "text",
    template: "",
    info: "",
    description: "",
    extension: "i",
    legacyId: 50,
  },
  {
    key: "TEXT",
    name: "Text",
    shortName: "",
    commonName: "Text",
    editorMode: "text",
    shikiLang: "text",
    template: "",
    info: "",
    description: "",
    extension: "txt",
    legacyId: 51,
  },
  {
    key: "SCALA",
    name: "Scala",
    shortName: "SCALA",
    commonName: "Scala",
    editorMode: "scala",
    shikiLang: "scala",
    template: "// Must be the same name as the problem code\r\nobject problemcode extends App {\r\n    \r\n}",
    info: "",
    description: "",
    extension: "scala",
    legacyId: 52,
  },
  {
    key: "SWIFT",
    name: "Swift",
    shortName: "",
    commonName: "Swift",
    editorMode: "swift",
    shikiLang: "swift",
    template: "",
    info: "",
    description: "",
    extension: "swift",
    legacyId: 54,
  },
  {
    key: "GAS32",
    name: "Assembly (x86)",
    shortName: "",
    commonName: "Assembly",
    editorMode: "assembly_x86",
    shikiLang: "asm",
    template: "",
    info: "",
    description: "",
    extension: "asm",
    legacyId: 56,
  },
  {
    key: "GASARM",
    name: "Assembly (ARM)",
    shortName: "",
    commonName: "Assembly",
    editorMode: "assembly_x86",
    shikiLang: "asm",
    template: "",
    info: "",
    description: "",
    extension: "asm",
    legacyId: 57,
  },
  {
    key: "GAS64",
    name: "Assembly (x64)",
    shortName: "",
    commonName: "Assembly",
    editorMode: "assembly_x86",
    shikiLang: "asm",
    template: "",
    info: "",
    description: "",
    extension: "asm",
    legacyId: 58,
  },
  {
    key: "SED",
    name: "Sed",
    shortName: "",
    commonName: "Sed",
    editorMode: "perl",
    shikiLang: "perl",
    template: "",
    info: "",
    description: "",
    extension: "sed",
    legacyId: 60,
  },
  {
    key: "JAVA",
    name: "Java",
    shortName: "",
    commonName: "Java",
    editorMode: "java",
    shikiLang: "java",
    template:
      "import java.io.*;\r\nimport java.util.*;\r\n\r\npublic class Main {\r\n    public static void main(String[] args) {\r\n\r\n    }\r\n}",
    info: "",
    description: "",
    extension: "java",
    legacyId: 61,
  },
  {
    key: "NASM64",
    name: "NASM64",
    shortName: "",
    commonName: "Assembly",
    editorMode: "assembly_x86",
    shikiLang: "asm",
    template: "",
    info: "",
    description: "",
    extension: "asm",
    legacyId: 62,
  },
  {
    key: "RKT",
    name: "Racket",
    shortName: "",
    commonName: "Racket",
    editorMode: "lisp",
    shikiLang: "racket",
    template: "#lang racket",
    info: "",
    description: "",
    extension: "rkt",
    legacyId: 63,
  },
  {
    key: "GROOVY",
    name: "Groovy",
    shortName: "Groovy",
    commonName: "Groovy",
    editorMode: "groovy",
    shikiLang: "groovy",
    template: "",
    info: "",
    description: "",
    extension: "groovy",
    legacyId: 64,
  },
  {
    key: "KOTLIN",
    name: "Kotlin",
    shortName: "",
    commonName: "Kotlin",
    editorMode: "kotlin",
    shikiLang: "kotlin",
    template: "",
    info: "",
    description: "",
    extension: "kt",
    legacyId: 67,
  },
  {
    key: "PIKE",
    name: "Pike",
    shortName: "",
    commonName: "Pike",
    editorMode: "pike",
    shikiLang: "text",
    template: "",
    info: "",
    description: "",
    extension: "pike",
    legacyId: 68,
  },
  {
    key: "CPP17",
    name: "C++17",
    shortName: "C++17",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 69,
  },
  {
    key: "SBCL",
    name: "Lisp",
    shortName: "Lisp",
    commonName: "Lisp",
    editorMode: "lisp",
    shikiLang: "lisp",
    template: "",
    info: "",
    description: "",
    extension: "cl",
    legacyId: 70,
  },
  {
    key: "C11",
    name: "C11",
    shortName: "",
    commonName: "C",
    editorMode: "c_cpp",
    shikiLang: "c",
    template: "#include <stdio.h>\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "c",
    legacyId: 72,
  },
  {
    key: "ZIG",
    name: "Zig",
    shortName: "",
    commonName: "Zig",
    editorMode: "zig",
    shikiLang: "zig",
    template: "",
    info: "",
    description: "",
    extension: "zig",
    legacyId: 75,
  },
  {
    key: "CPP20",
    name: "C++20",
    shortName: "C++20",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
    legacyId: 76,
  },

  // Executors the judge ships that DMOJ's fixture predates.
  {
    key: "ALGL68",
    name: "ALGOL 68",
    shortName: "",
    commonName: "ALGOL 68",
    editorMode: "text",
    shikiLang: "text",
    template: "",
    info: "",
    description: "",
    extension: "a",
  },
  {
    key: "BASH",
    name: "Bash",
    shortName: "",
    commonName: "Bash",
    editorMode: "sh",
    shikiLang: "bash",
    template: "",
    info: "",
    description: "",
    extension: "sh",
  },
  {
    key: "C23",
    name: "C23",
    shortName: "",
    commonName: "C",
    editorMode: "c_cpp",
    shikiLang: "c",
    template: "#include <stdio.h>\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "c",
  },
  {
    key: "CLPP14",
    name: "Clang++14",
    shortName: "Clang++14",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
  },
  {
    key: "CLPP17",
    name: "Clang++17",
    shortName: "Clang++17",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
  },
  {
    key: "CLPP20",
    name: "Clang++20",
    shortName: "Clang++20",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
  },
  {
    key: "CLPP23",
    name: "Clang++23",
    shortName: "Clang++23",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
  },
  {
    key: "CPP23",
    name: "C++23",
    shortName: "C++23",
    commonName: "C++",
    editorMode: "c_cpp",
    shikiLang: "cpp",
    template:
      "#include <bits/stdc++.h>\r\n\r\nusing namespace std;\r\n\r\nint main() {\r\n    return 0;\r\n}",
    info: "",
    description: "",
    extension: "cpp",
  },
  {
    key: "LEAN4",
    name: "Lean 4",
    shortName: "",
    commonName: "Lean",
    editorMode: "text",
    shikiLang: "lean",
    template: "",
    info: "",
    description: "",
    extension: "lean",
  },
  {
    key: "LLC",
    name: "LLVM IR",
    shortName: "",
    commonName: "LLVM",
    editorMode: "text",
    shikiLang: "llvm",
    template: "",
    info: "",
    description: "",
    extension: "ll",
  },
  {
    key: "NODEJS",
    name: "JavaScript (Node.js)",
    shortName: "Node.js",
    commonName: "JavaScript",
    editorMode: "javascript",
    shikiLang: "javascript",
    template: "",
    info: "",
    description: "",
    extension: "js",
  },
];

export const SEED_NAVIGATION: SeedNavItem[] = [
  {
    legacyId: 1,
    order: 1,
    key: "problems",
    label: "Problems",
    path: "/problems/",
    regex: "^/problem",
    parentLegacyId: null,
  },
  {
    legacyId: 2,
    order: 2,
    key: "submit",
    label: "Submissions",
    path: "/submissions/",
    regex: "^/submi|^/src/",
    parentLegacyId: null,
  },
  {
    legacyId: 3,
    order: 3,
    key: "user",
    label: "Users",
    path: "/users/",
    regex: "^/user",
    parentLegacyId: null,
  },
  {
    legacyId: 5,
    order: 5,
    key: "contest",
    label: "Contests",
    path: "/contests/",
    regex: "^/contest",
    parentLegacyId: null,
  },
  {
    legacyId: 6,
    order: 6,
    key: "about",
    label: "About",
    path: "/about/",
    regex: "^/about/$",
    parentLegacyId: null,
  },
  {
    legacyId: 7,
    order: 7,
    key: "status",
    label: "Status",
    path: "/status/",
    regex: "^/status/$|^/judge/",
    parentLegacyId: 6,
  },
];
