// Transcribed from DMOJ's judge/jinja2/markdown/bleach_whitelist.py.
//
// ALL_STYLES is `standard_styles + all_prefixed_styles` with the entries that are not plain
// property names removed (that list is MDN's CSS reference, so it also contains selectors,
// at-rules, functions and `<type>` placeholders, which a CSS property allowlist never
// matches). MATHML_TAGS and MATHML_ATTRS are `mathml_tags` and `mathml_attrs` verbatim.
//
// Do not edit by hand: re-derive it from the DMOJ source if the upstream list changes.

export const ALL_STYLES: readonly string[] = [
  "-moz-appearance",
  "-moz-binding",
  "-moz-border-bottom-colors",
  "-moz-border-end",
  "-moz-border-end-color",
  "-moz-border-end-style",
  "-moz-border-end-width",
  "-moz-border-left-colors",
  "-moz-border-right-colors",
  "-moz-border-start",
  "-moz-border-start-color",
  "-moz-border-start-style",
  "-moz-border-start-width",
  "-moz-border-top-colors",
  "-moz-box-align",
  "-moz-box-direction",
  "-moz-box-flex",
  "-moz-box-ordinal-group",
  "-moz-box-orient",
  "-moz-box-pack",
  "-moz-column-count",
  "-moz-column-fill",
  "-moz-column-gap",
  "-moz-column-rule",
  "-moz-column-rule-color",
  "-moz-column-rule-style",
  "-moz-column-rule-width",
  "-moz-column-width",
  "-moz-columns",
  "-moz-control-character-visibility",
  "-moz-float-edge",
  "-moz-force-broken-image-icon",
  "-moz-hyphens",
  "-moz-image-region",
  "-moz-margin-end",
  "-moz-margin-start",
  "-moz-math-display",
  "-moz-math-variant",
  "-moz-orient",
  "-moz-osx-font-smoothing",
  "-moz-outline-radius",
  "-moz-outline-radius-bottomleft",
  "-moz-outline-radius-bottomright",
  "-moz-outline-radius-topleft",
  "-moz-outline-radius-topright",
  "-moz-padding-end",
  "-moz-padding-start",
  "-moz-script-level",
  "-moz-script-min-size",
  "-moz-script-size-multiplier",
  "-moz-stack-sizing",
  "-moz-tab-size",
  "-moz-text-align-last",
  "-moz-text-size-adjust",
  "-moz-user-focus",
  "-moz-user-input",
  "-moz-user-modify",
  "-moz-user-select",
  "-moz-window-dragging",
  "-moz-window-shadow",
  "-ms-accelerator",
  "-ms-block-progression",
  "-ms-content-zoom-chaining",
  "-ms-content-zoom-limit",
  "-ms-content-zoom-limit-max",
  "-ms-content-zoom-limit-min",
  "-ms-content-zoom-snap",
  "-ms-content-zoom-snap-points",
  "-ms-content-zoom-snap-type",
  "-ms-content-zooming",
  "-ms-flex-align",
  "-ms-flex-item-align",
  "-ms-flex-line-pack",
  "-ms-flex-negative",
  "-ms-flex-order",
  "-ms-flex-pack",
  "-ms-flex-positive",
  "-ms-flex-preferred-size",
  "-ms-flow-from",
  "-ms-flow-into",
  "-ms-grid-column",
  "-ms-grid-column-align",
  "-ms-grid-column-span",
  "-ms-grid-columns",
  "-ms-grid-row",
  "-ms-grid-row-align",
  "-ms-grid-row-span",
  "-ms-grid-rows",
  "-ms-high-contrast-adjust",
  "-ms-hyphenate-limit-chars",
  "-ms-hyphenate-limit-lines",
  "-ms-hyphenate-limit-zone",
  "-ms-hyphens",
  "-ms-ime-align",
  "-ms-interpolation-mode",
  "-ms-overflow-style",
  "-ms-scroll-chaining",
  "-ms-scroll-limit",
  "-ms-scroll-limit-x-max",
  "-ms-scroll-limit-x-min",
  "-ms-scroll-limit-y-max",
  "-ms-scroll-limit-y-min",
  "-ms-scroll-rails",
  "-ms-scroll-snap-points-x",
  "-ms-scroll-snap-points-y",
  "-ms-scroll-snap-type",
  "-ms-scroll-snap-x",
  "-ms-scroll-snap-y",
  "-ms-scroll-translation",
  "-ms-scrollbar-3dlight-color",
  "-ms-text-combine-horizontal",
  "-ms-text-size-adjust",
  "-ms-touch-select",
  "-ms-user-select",
  "-ms-wrap-flow",
  "-ms-wrap-margin",
  "-ms-wrap-through",
  "-webkit-app-region",
  "-webkit-appearance",
  "-webkit-aspect-ratio",
  "-webkit-backdrop-filter",
  "-webkit-backface-visibility",
  "-webkit-background-composite",
  "-webkit-border-after",
  "-webkit-border-after-color",
  "-webkit-border-after-style",
  "-webkit-border-after-width",
  "-webkit-border-before",
  "-webkit-border-before-color",
  "-webkit-border-before-style",
  "-webkit-border-before-width",
  "-webkit-border-end",
  "-webkit-border-end-color",
  "-webkit-border-end-style",
  "-webkit-border-end-width",
  "-webkit-border-fit",
  "-webkit-border-horizontal-spacing",
  "-webkit-border-start",
  "-webkit-border-start-color",
  "-webkit-border-start-style",
  "-webkit-border-start-width",
  "-webkit-border-vertical-spacing",
  "-webkit-box-align",
  "-webkit-box-decoration-break",
  "-webkit-box-direction",
  "-webkit-box-flex",
  "-webkit-box-flex-group",
  "-webkit-box-lines",
  "-webkit-box-ordinal-group",
  "-webkit-box-orient",
  "-webkit-box-pack",
  "-webkit-box-reflect",
  "-webkit-clip-path",
  "-webkit-color-correction",
  "-webkit-column-axis",
  "-webkit-column-break-after",
  "-webkit-column-break-before",
  "-webkit-column-break-inside",
  "-webkit-column-count",
  "-webkit-column-gap",
  "-webkit-column-rule",
  "-webkit-column-rule-color",
  "-webkit-column-rule-style",
  "-webkit-column-rule-width",
  "-webkit-column-span",
  "-webkit-column-width",
  "-webkit-columns",
  "-webkit-cursor-visibility",
  "-webkit-dashboard-region",
  "-webkit-filter",
  "-webkit-flow-from",
  "-webkit-flow-into",
  "-webkit-font-feature-settings",
  "-webkit-font-kerning",
  "-webkit-font-size-delta",
  "-webkit-font-smoothing",
  "-webkit-font-variant-ligatures",
  "-webkit-grid",
  "-webkit-grid-area",
  "-webkit-grid-auto-columns",
  "-webkit-grid-auto-flow",
  "-webkit-grid-auto-rows",
  "-webkit-grid-column",
  "-webkit-grid-column-end",
  "-webkit-grid-column-start",
  "-webkit-grid-row",
  "-webkit-grid-row-end",
  "-webkit-grid-row-start",
  "-webkit-grid-template",
  "-webkit-grid-template-areas",
  "-webkit-grid-template-columns",
  "-webkit-grid-template-rows",
  "-webkit-highlight",
  "-webkit-hyphenate-character",
  "-webkit-hyphenate-limit-after",
  "-webkit-hyphenate-limit-before",
  "-webkit-hyphenate-limit-lines",
  "-webkit-hyphens",
  "-webkit-initial-letter",
  "-webkit-justify-self",
  "-webkit-line-align",
  "-webkit-line-box-contain",
  "-webkit-line-break",
  "-webkit-line-clamp",
  "-webkit-line-grid",
  "-webkit-line-snap",
  "-webkit-locale",
  "-webkit-logical-height",
  "-webkit-logical-width",
  "-webkit-margin-after",
  "-webkit-margin-after-collapse",
  "-webkit-margin-before",
  "-webkit-margin-before-collapse",
  "-webkit-margin-bottom-collapse",
  "-webkit-margin-collapse",
  "-webkit-margin-end",
  "-webkit-margin-start",
  "-webkit-margin-top-collapse",
  "-webkit-marquee",
  "-webkit-marquee-direction",
  "-webkit-marquee-increment",
  "-webkit-marquee-repetition",
  "-webkit-marquee-speed",
  "-webkit-marquee-style",
  "-webkit-mask",
  "-webkit-mask-box-image",
  "-webkit-mask-box-image-outset",
  "-webkit-mask-box-image-repeat",
  "-webkit-mask-box-image-slice",
  "-webkit-mask-box-image-source",
  "-webkit-mask-box-image-width",
  "-webkit-mask-clip",
  "-webkit-mask-composite",
  "-webkit-mask-image",
  "-webkit-mask-origin",
  "-webkit-mask-position",
  "-webkit-mask-position-x",
  "-webkit-mask-position-y",
  "-webkit-mask-repeat",
  "-webkit-mask-repeat-x",
  "-webkit-mask-repeat-y",
  "-webkit-mask-size",
  "-webkit-mask-source-type",
  "-webkit-max-logical-height",
  "-webkit-max-logical-width",
  "-webkit-min-logical-height",
  "-webkit-min-logical-width",
  "-webkit-nbsp-mode",
  "-webkit-overflow-scrolling",
  "-webkit-padding-after",
  "-webkit-padding-before",
  "-webkit-padding-end",
  "-webkit-padding-start",
  "-webkit-perspective",
  "-webkit-perspective-origin",
  "-webkit-perspective-origin-x",
  "-webkit-perspective-origin-y",
  "-webkit-print-color-adjust",
  "-webkit-region-break-after",
  "-webkit-region-break-before",
  "-webkit-region-break-inside",
  "-webkit-region-fragment",
  "-webkit-rtl-ordering",
  "-webkit-ruby-position",
  "-webkit-scroll-snap-coordinate",
  "-webkit-scroll-snap-destination",
  "-webkit-scroll-snap-points-x",
  "-webkit-scroll-snap-points-y",
  "-webkit-scroll-snap-type",
  "-webkit-shape-image-threshold",
  "-webkit-shape-margin",
  "-webkit-shape-outside",
  "-webkit-tap-highlight-color",
  "-webkit-text-align-last",
  "-webkit-text-combine",
  "-webkit-text-decoration-color",
  "-webkit-text-decoration-line",
  "-webkit-text-decoration-skip",
  "-webkit-text-decoration-style",
  "-webkit-text-decorations-in-effect",
  "-webkit-text-emphasis",
  "-webkit-text-emphasis-color",
  "-webkit-text-emphasis-position",
  "-webkit-text-emphasis-style",
  "-webkit-text-fill-color",
  "-webkit-text-justify",
  "-webkit-text-orientation",
  "-webkit-text-security",
  "-webkit-text-size-adjust",
  "-webkit-text-stroke",
  "-webkit-text-stroke-color",
  "-webkit-text-stroke-width",
  "-webkit-text-underline-position",
  "-webkit-touch-callout",
  "-webkit-transform",
  "-webkit-transform-origin",
  "-webkit-transform-origin-x",
  "-webkit-transform-origin-y",
  "-webkit-transform-origin-z",
  "-webkit-transform-style",
  "-webkit-user-drag",
  "-webkit-user-modify",
  "-webkit-user-select",
  "-webkit-writing-mode",
  "align-content",
  "align-items",
  "align-self",
  "all",
  "animation",
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-timing-function",
  "backface-visibility",
  "background",
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-repeat",
  "background-size",
  "border",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color",
  "border-image",
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "bottom",
  "box-decoration-break",
  "box-shadow",
  "box-sizing",
  "break-after",
  "break-before",
  "break-inside",
  "caption-side",
  "ch",
  "clear",
  "clip",
  "clip-path",
  "cm",
  "color",
  "column-count",
  "column-fill",
  "column-gap",
  "column-rule",
  "column-rule-color",
  "column-rule-style",
  "column-rule-width",
  "column-span",
  "column-width",
  "columns",
  "content",
  "counter-increment",
  "counter-reset",
  "cursor",
  "deg",
  "direction",
  "display",
  "dpcm",
  "dpi",
  "dppx",
  "em",
  "empty-cells",
  "ex",
  "filter",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "float",
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-language-override",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-variant",
  "font-variant-alternates",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-weight",
  "grad",
  "grid",
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-position",
  "grid-auto-rows",
  "grid-column",
  "grid-column-end",
  "grid-column-start",
  "grid-row",
  "grid-row-end",
  "grid-row-start",
  "grid-template",
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "height",
  "hyphens",
  "hz",
  "image-orientation",
  "image-rendering",
  "image-resolution",
  "ime-mode",
  "in",
  "inherit",
  "initial",
  "isolation",
  "justify-content",
  "justify-self",
  "khz",
  "left",
  "letter-spacing",
  "line-break",
  "line-height",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "margin-top",
  "marks",
  "mask",
  "mask-source-type",
  "mask-type",
  "max-height",
  "max-width",
  "min-height",
  "min-width",
  "mix-blend-mode",
  "mm",
  "ms",
  "object-fit",
  "object-position",
  "opacity",
  "order",
  "orphans",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "padding",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "padding-top",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "pc",
  "perspective",
  "perspective-origin",
  "perspective-origin-x",
  "perspective-origin-y",
  "pointer-events",
  "position",
  "pt",
  "px",
  "quotes",
  "rad",
  "rem",
  "resize",
  "right",
  "ruby-align",
  "ruby-merge",
  "ruby-position",
  "s",
  "scroll-behavior",
  "shape-image-threshold",
  "shape-margin",
  "shape-outside",
  "tab-size",
  "table-layout",
  "text-align",
  "text-align-last",
  "text-combine-upright",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-style",
  "text-emphasis",
  "text-emphasis-color",
  "text-emphasis-position",
  "text-emphasis-style",
  "text-indent",
  "text-justify",
  "text-orientation",
  "text-overflow",
  "text-rendering",
  "text-shadow",
  "text-transform",
  "text-underline-position",
  "top",
  "touch-action",
  "transform",
  "transform-origin",
  "transform-origin-x",
  "transform-origin-y",
  "transform-origin-z",
  "transform-style",
  "transition",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "turn",
  "unicode-bidi",
  "unicode-range",
  "unset",
  "vertical-align",
  "vh",
  "visibility",
  "vmax",
  "vmin",
  "vw",
  "white-space",
  "widows",
  "width",
  "will-change",
  "word-break",
  "word-spacing",
  "word-wrap",
  "writing-mode",
  "z-index",
];

export const MATHML_TAGS: readonly string[] = [
  "abs",
  "and",
  "annotation",
  "annotation-xml",
  "apply",
  "approx",
  "arccos",
  "arccosh",
  "arccot",
  "arccoth",
  "arccsc",
  "arccsch",
  "arcsec",
  "arcsech",
  "arcsin",
  "arcsinh",
  "arctan",
  "arctanh",
  "arg",
  "bind",
  "bvar",
  "card",
  "cartesianproduct",
  "cbytes",
  "ceiling",
  "cerror",
  "ci",
  "cn",
  "codomain",
  "complexes",
  "compose",
  "condition",
  "conjugate",
  "cos",
  "cosh",
  "cot",
  "coth",
  "cs",
  "csc",
  "csch",
  "csymbol",
  "curl",
  "declare",
  "degree",
  "determinant",
  "diff",
  "divergence",
  "divide",
  "domain",
  "domainofapplication",
  "emptyset",
  "encoding",
  "eq",
  "equivalent",
  "eulergamma",
  "exists",
  "exp",
  "exponentiale",
  "factorial",
  "factorof",
  "false",
  "floor",
  "fn",
  "forall",
  "function",
  "gcd",
  "geq",
  "grad",
  "gt",
  "ident",
  "image",
  "imaginary",
  "imaginaryi",
  "implies",
  "in",
  "infinity",
  "int",
  "integers",
  "intersect",
  "interval",
  "inverse",
  "lambda",
  "laplacian",
  "lcm",
  "leq",
  "limit",
  "list",
  "ln",
  "log",
  "logbase",
  "lowlimit",
  "lt",
  "maction",
  "malign",
  "maligngroup",
  "malignmark",
  "malignscope",
  "math",
  "matrix",
  "matrixrow",
  "max",
  "mean",
  "median",
  "menclose",
  "merror",
  "mfenced",
  "mfrac",
  "mfraction",
  "mglyph",
  "mi",
  "min",
  "minus",
  "mlabeledtr",
  "mlongdiv",
  "mmultiscripts",
  "mn",
  "mo",
  "mode",
  "moment",
  "momentabout",
  "mover",
  "mpadded",
  "mphantom",
  "mprescripts",
  "mroot",
  "mrow",
  "ms",
  "mscarries",
  "mscarry",
  "msgroup",
  "msline",
  "mspace",
  "msqrt",
  "msrow",
  "mstack",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "naturalnumbers",
  "neq",
  "none",
  "not",
  "notanumber",
  "notin",
  "notprsubset",
  "notsubset",
  "or",
  "otherwise",
  "outerproduct",
  "partialdiff",
  "pi",
  "piece",
  "piecewice",
  "piecewise",
  "plus",
  "power",
  "primes",
  "product",
  "prsubset",
  "quotient",
  "rationals",
  "real",
  "reals",
  "reln",
  "rem",
  "root",
  "scalarproduct",
  "sdev",
  "sec",
  "sech",
  "select",
  "selector",
  "semantics",
  "sep",
  "set",
  "setdiff",
  "share",
  "sin",
  "sinh",
  "span",
  "subset",
  "sum",
  "tan",
  "tanh",
  "tendsto",
  "times",
  "transpose",
  "true",
  "union",
  "uplimit",
  "var",
  "variance",
  "vector",
  "vectorproduct",
  "xor",
];

/** MathML attribute allowlist: an element name to the attributes bleach keeps on it. */
interface MathmlAttributeAllowlist {
  readonly [tagName: string]: readonly string[];
}

export const MATHML_ATTRS: MathmlAttributeAllowlist = {
  abs: ["href", "id", "mathbackground", "mathcolor"],
  and: ["href", "id", "mathbackground", "mathcolor"],
  annotation: ["encoding", "href", "id", "mathbackground", "mathcolor"],
  "annotation-xml": ["href", "id", "mathbackground", "mathcolor"],
  apply: ["href", "id", "mathbackground", "mathcolor"],
  approx: ["href", "id", "mathbackground", "mathcolor"],
  arccos: ["href", "id", "mathbackground", "mathcolor"],
  arccosh: ["href", "id", "mathbackground", "mathcolor"],
  arccot: ["href", "id", "mathbackground", "mathcolor"],
  arccoth: ["href", "id", "mathbackground", "mathcolor"],
  arccsc: ["href", "id", "mathbackground", "mathcolor"],
  arccsch: ["href", "id", "mathbackground", "mathcolor"],
  arcsec: ["href", "id", "mathbackground", "mathcolor"],
  arcsech: ["href", "id", "mathbackground", "mathcolor"],
  arcsin: ["href", "id", "mathbackground", "mathcolor"],
  arcsinh: ["href", "id", "mathbackground", "mathcolor"],
  arctan: ["href", "id", "mathbackground", "mathcolor"],
  arctanh: ["href", "id", "mathbackground", "mathcolor"],
  arg: ["href", "id", "mathbackground", "mathcolor"],
  bind: ["href", "id", "mathbackground", "mathcolor"],
  bvar: ["href", "id", "mathbackground", "mathcolor"],
  card: ["href", "id", "mathbackground", "mathcolor"],
  cartesianproduct: ["href", "id", "mathbackground", "mathcolor"],
  cbytes: ["href", "id", "mathbackground", "mathcolor"],
  ceiling: ["href", "id", "mathbackground", "mathcolor"],
  cerror: ["href", "id", "mathbackground", "mathcolor"],
  ci: ["href", "id", "mathbackground", "mathcolor"],
  cn: ["href", "id", "mathbackground", "mathcolor"],
  codomain: ["href", "id", "mathbackground", "mathcolor"],
  complexes: ["href", "id", "mathbackground", "mathcolor"],
  compose: ["href", "id", "mathbackground", "mathcolor"],
  condition: ["href", "id", "mathbackground", "mathcolor"],
  conjugate: ["href", "id", "mathbackground", "mathcolor"],
  cos: ["href", "id", "mathbackground", "mathcolor"],
  cosh: ["href", "id", "mathbackground", "mathcolor"],
  cot: ["href", "id", "mathbackground", "mathcolor"],
  coth: ["href", "id", "mathbackground", "mathcolor"],
  cs: ["href", "id", "mathbackground", "mathcolor"],
  csc: ["href", "id", "mathbackground", "mathcolor"],
  csch: ["href", "id", "mathbackground", "mathcolor"],
  csymbol: ["href", "id", "mathbackground", "mathcolor"],
  curl: ["href", "id", "mathbackground", "mathcolor"],
  declare: ["href", "id", "mathbackground", "mathcolor"],
  degree: ["href", "id", "mathbackground", "mathcolor"],
  determinant: ["href", "id", "mathbackground", "mathcolor"],
  diff: ["href", "id", "mathbackground", "mathcolor"],
  divergence: ["href", "id", "mathbackground", "mathcolor"],
  divide: ["href", "id", "mathbackground", "mathcolor"],
  domain: ["href", "id", "mathbackground", "mathcolor"],
  domainofapplication: ["href", "id", "mathbackground", "mathcolor"],
  emptyset: ["href", "id", "mathbackground", "mathcolor"],
  encoding: ["href", "id", "mathbackground", "mathcolor"],
  eq: ["href", "id", "mathbackground", "mathcolor"],
  equivalent: ["href", "id", "mathbackground", "mathcolor"],
  eulergamma: ["href", "id", "mathbackground", "mathcolor"],
  exists: ["href", "id", "mathbackground", "mathcolor"],
  exp: ["href", "id", "mathbackground", "mathcolor"],
  exponentiale: ["href", "id", "mathbackground", "mathcolor"],
  factorial: ["href", "id", "mathbackground", "mathcolor"],
  factorof: ["href", "id", "mathbackground", "mathcolor"],
  false: ["href", "id", "mathbackground", "mathcolor"],
  floor: ["href", "id", "mathbackground", "mathcolor"],
  fn: ["href", "id", "mathbackground", "mathcolor"],
  forall: ["href", "id", "mathbackground", "mathcolor"],
  function: ["href", "id", "mathbackground", "mathcolor"],
  gcd: ["href", "id", "mathbackground", "mathcolor"],
  geq: ["href", "id", "mathbackground", "mathcolor"],
  grad: ["href", "id", "mathbackground", "mathcolor"],
  gt: ["href", "id", "mathbackground", "mathcolor"],
  ident: ["href", "id", "mathbackground", "mathcolor"],
  image: ["href", "id", "mathbackground", "mathcolor"],
  imaginary: ["href", "id", "mathbackground", "mathcolor"],
  imaginaryi: ["href", "id", "mathbackground", "mathcolor"],
  implies: ["href", "id", "mathbackground", "mathcolor"],
  in: ["href", "id", "mathbackground", "mathcolor"],
  infinity: ["href", "id", "mathbackground", "mathcolor"],
  int: ["href", "id", "mathbackground", "mathcolor"],
  integers: ["href", "id", "mathbackground", "mathcolor"],
  intersect: ["href", "id", "mathbackground", "mathcolor"],
  interval: ["href", "id", "mathbackground", "mathcolor"],
  inverse: ["href", "id", "mathbackground", "mathcolor"],
  lambda: ["href", "id", "mathbackground", "mathcolor"],
  laplacian: ["href", "id", "mathbackground", "mathcolor"],
  lcm: ["href", "id", "mathbackground", "mathcolor"],
  leq: ["href", "id", "mathbackground", "mathcolor"],
  limit: ["href", "id", "mathbackground", "mathcolor"],
  list: ["href", "id", "mathbackground", "mathcolor"],
  ln: ["href", "id", "mathbackground", "mathcolor"],
  log: ["href", "id", "mathbackground", "mathcolor"],
  logbase: ["href", "id", "mathbackground", "mathcolor"],
  lowlimit: ["href", "id", "mathbackground", "mathcolor"],
  lt: ["href", "id", "mathbackground", "mathcolor"],
  maction: ["actiontype", "href", "id", "mathbackground", "mathcolor", "selection"],
  malign: ["href", "id", "mathbackground", "mathcolor"],
  maligngroup: ["groupalign", "href", "id", "mathbackground", "mathcolor"],
  malignmark: ["edge", "href", "id", "mathbackground", "mathcolor"],
  malignscope: ["href", "id", "mathbackground", "mathcolor"],
  math: [
    "altimg",
    "altimg-height",
    "altimg-valign",
    "altimg-width",
    "alttext",
    "dir",
    "display",
    "href",
    "id",
    "mathbackground",
    "mathcolor",
    "overflow",
    "xmlns",
  ],
  matrix: ["href", "id", "mathbackground", "mathcolor"],
  matrixrow: ["href", "id", "mathbackground", "mathcolor"],
  max: ["href", "id", "mathbackground", "mathcolor"],
  mean: ["href", "id", "mathbackground", "mathcolor"],
  median: ["href", "id", "mathbackground", "mathcolor"],
  menclose: ["href", "id", "mathbackground", "mathcolor", "notation"],
  merror: ["href", "id", "mathbackground", "mathcolor"],
  mfenced: ["close", "href", "id", "mathbackground", "mathcolor", "open", "separators"],
  mfrac: ["bevelled", "denomalign", "href", "id", "linethickness", "mathbackground", "mathcolor", "numalign"],
  mfraction: ["href", "id", "mathbackground", "mathcolor"],
  mglyph: ["height", "href", "id", "mathbackground", "mathcolor", "src", "width"],
  mi: ["dir", "href", "id", "mathbackground", "mathcolor", "mathsize", "mathvariant"],
  min: ["href", "id", "mathbackground", "mathcolor"],
  minus: ["href", "id", "mathbackground", "mathcolor"],
  mlabeledtr: ["columnalign", "href", "id", "mathbackground", "mathcolor"],
  mlongdiv: ["href", "id", "longdivstyle", "mathbackground", "mathcolor"],
  mmultiscripts: ["href", "id", "mathbackground", "mathcolor", "subscriptshift", "supscriptshift"],
  mn: ["href", "id", "mathbackground", "mathcolor", "mathsize", "mathvariant"],
  mo: [
    "accent",
    "dir",
    "fence",
    "form",
    "href",
    "id",
    "indentalign",
    "indentalignfirst",
    "indentalignlast",
    "indentshift",
    "indentshiftfirst",
    "indentshiftlast",
    "indenttarget",
    "largeop",
    "linebreak",
    "linebreakmultchar",
    "linebreakstyle",
    "lineleading",
    "lspace",
    "mathbackground",
    "mathcolor",
    "mathsize",
    "mathvariant",
    "maxsize",
    "minsize",
    "movablelimits",
    "rspace",
    "separator",
    "stretchy",
    "symmetric",
  ],
  mode: ["href", "id", "mathbackground", "mathcolor"],
  moment: ["href", "id", "mathbackground", "mathcolor"],
  momentabout: ["href", "id", "mathbackground", "mathcolor"],
  mover: ["accent", "align", "href", "id", "mathbackground", "mathcolor"],
  mpadded: ["depth", "height", "href", "id", "lspace", "mathbackground", "mathcolor", "voffset", "width"],
  mphantom: ["href", "id", "mathbackground", "mathcolor"],
  mprescripts: ["href", "id", "mathbackground", "mathcolor"],
  mroot: ["href", "id", "mathbackground", "mathcolor"],
  mrow: ["dir", "href", "id", "mathbackground", "mathcolor"],
  ms: ["dir", "href", "id", "lquote", "mathbackground", "mathcolor", "mathsize", "mathvariant", "rquote"],
  mscarries: ["href", "id", "location", "mathbackground", "mathcolor", "position"],
  mscarry: ["crossout", "href", "id", "mathbackground", "mathcolor"],
  msgroup: ["href", "id", "mathbackground", "mathcolor", "position", "shift"],
  msline: ["href", "id", "length", "mathbackground", "mathcolor", "position"],
  mspace: [
    "height",
    "href",
    "id",
    "indentalign",
    "indentalignfirst",
    "indentalignlast",
    "indentshift",
    "indentshiftfirst",
    "indentshiftlast",
    "indenttarget",
    "linebreak",
    "linebreakmultchar",
    "linebreakstyle",
    "lineleading",
    "mathbackground",
    "mathcolor",
    "width",
  ],
  msqrt: ["href", "id", "mathbackground", "mathcolor"],
  msrow: ["href", "id", "mathbackground", "mathcolor", "position"],
  mstack: ["align", "charalign", "href", "id", "mathbackground", "mathcolor", "stackalign"],
  mstyle: [
    "decimalpoint",
    "displaystyle",
    "href",
    "id",
    "infixlinebreakstyle",
    "mathbackground",
    "mathcolor",
    "scriptlevel",
    "scriptminsize",
    "scriptsizemultiplier",
  ],
  msub: ["href", "id", "mathbackground", "mathcolor", "subscriptshift"],
  msubsup: ["href", "id", "mathbackground", "mathcolor", "subscriptshift", "supscriptshift"],
  msup: ["href", "id", "mathbackground", "mathcolor", "supscriptshift"],
  mtable: [
    "align",
    "alignmentscope",
    "columnalign",
    "columnlines",
    "columnspacing",
    "columnwidth",
    "displaystyle",
    "equalcolumns",
    "equalrows",
    "frame",
    "framespacing",
    "groupalign",
    "href",
    "id",
    "mathbackground",
    "mathcolor",
    "minlabelspacing",
    "rowalign",
    "rowlines",
    "rowspacing",
    "side",
    "width",
  ],
  mtd: [
    "columnalign",
    "columnspan",
    "groupalign",
    "href",
    "id",
    "mathbackground",
    "mathcolor",
    "rowalign",
    "rowspan",
  ],
  mtext: ["dir", "href", "id", "mathbackground", "mathcolor", "mathsize", "mathvariant"],
  mtr: ["columnalign", "groupalign", "href", "id", "mathbackground", "mathcolor", "rowalign"],
  munder: ["accentunder", "align", "href", "id", "mathbackground", "mathcolor"],
  munderover: ["accent", "accentunder", "align", "href", "id", "mathbackground", "mathcolor"],
  naturalnumbers: ["href", "id", "mathbackground", "mathcolor"],
  neq: ["href", "id", "mathbackground", "mathcolor"],
  none: ["href", "id", "mathbackground", "mathcolor"],
  not: ["href", "id", "mathbackground", "mathcolor"],
  notanumber: ["href", "id", "mathbackground", "mathcolor"],
  notin: ["href", "id", "mathbackground", "mathcolor"],
  notprsubset: ["href", "id", "mathbackground", "mathcolor"],
  notsubset: ["href", "id", "mathbackground", "mathcolor"],
  or: ["href", "id", "mathbackground", "mathcolor"],
  otherwise: ["href", "id", "mathbackground", "mathcolor"],
  outerproduct: ["href", "id", "mathbackground", "mathcolor"],
  partialdiff: ["href", "id", "mathbackground", "mathcolor"],
  pi: ["href", "id", "mathbackground", "mathcolor"],
  piece: ["href", "id", "mathbackground", "mathcolor"],
  piecewice: ["href", "id", "mathbackground", "mathcolor"],
  piecewise: ["href", "id", "mathbackground", "mathcolor"],
  plus: ["href", "id", "mathbackground", "mathcolor"],
  power: ["href", "id", "mathbackground", "mathcolor"],
  primes: ["href", "id", "mathbackground", "mathcolor"],
  product: ["href", "id", "mathbackground", "mathcolor"],
  prsubset: ["href", "id", "mathbackground", "mathcolor"],
  quotient: ["href", "id", "mathbackground", "mathcolor"],
  rationals: ["href", "id", "mathbackground", "mathcolor"],
  real: ["href", "id", "mathbackground", "mathcolor"],
  reals: ["href", "id", "mathbackground", "mathcolor"],
  reln: ["href", "id", "mathbackground", "mathcolor"],
  rem: ["href", "id", "mathbackground", "mathcolor"],
  root: ["href", "id", "mathbackground", "mathcolor"],
  scalarproduct: ["href", "id", "mathbackground", "mathcolor"],
  sdev: ["href", "id", "mathbackground", "mathcolor"],
  sec: ["href", "id", "mathbackground", "mathcolor"],
  sech: ["href", "id", "mathbackground", "mathcolor"],
  select: ["href", "id", "mathbackground", "mathcolor"],
  selector: ["href", "id", "mathbackground", "mathcolor"],
  semantics: ["href", "id", "mathbackground", "mathcolor"],
  sep: ["href", "id", "mathbackground", "mathcolor"],
  set: ["href", "id", "mathbackground", "mathcolor"],
  setdiff: ["href", "id", "mathbackground", "mathcolor"],
  share: ["href", "id", "mathbackground", "mathcolor"],
  sin: ["href", "id", "mathbackground", "mathcolor"],
  sinh: ["href", "id", "mathbackground", "mathcolor"],
  span: ["href", "id", "mathbackground", "mathcolor"],
  subset: ["href", "id", "mathbackground", "mathcolor"],
  sum: ["href", "id", "mathbackground", "mathcolor"],
  tan: ["href", "id", "mathbackground", "mathcolor"],
  tanh: ["href", "id", "mathbackground", "mathcolor"],
  tendsto: ["href", "id", "mathbackground", "mathcolor"],
  times: ["href", "id", "mathbackground", "mathcolor"],
  transpose: ["href", "id", "mathbackground", "mathcolor"],
  true: ["href", "id", "mathbackground", "mathcolor"],
  union: ["href", "id", "mathbackground", "mathcolor"],
  uplimit: ["href", "id", "mathbackground", "mathcolor"],
  var: ["href", "id", "mathbackground", "mathcolor"],
  variance: ["href", "id", "mathbackground", "mathcolor"],
  vector: ["href", "id", "mathbackground", "mathcolor"],
  vectorproduct: ["href", "id", "mathbackground", "mathcolor"],
  xor: ["href", "id", "mathbackground", "mathcolor"],
};
