/**
 * `booklet` builds the Typst source for a division booklet: a cover page listing the
 * problems, then one problem per section separated by page breaks, each with the
 * Codeforces-style header and a footer naming the division and the problem.
 */

import { typstEscapeString, typstOptional } from "./escape.js";
import type { NormaliseOptions } from "./markdown.js";
import { markdownToTypstBody, type ProblemMeta, statementArguments } from "./statement.js";

export interface BookletProblem {
  readonly meta: ProblemMeta;
  readonly statement: string;
}

export interface ContestMeta {
  readonly title: string;
  readonly subtitle?: string | undefined;
  readonly date?: string | undefined;
  /** Small print on the cover: rules, judging notes, how to submit. Markdown. */
  readonly note?: string | undefined;
  /** Path to a logo image, relative to the compile root. */
  readonly logo?: string | undefined;
  /** Footer text on the left of every problem page; the title by default. */
  readonly footerText?: string | undefined;
  /** Letters for the problems, in order. Defaults to A, B, C, ... */
  readonly labels?: readonly string[] | undefined;
}

export interface BookletOptions extends NormaliseOptions {
  readonly template?: string;
  readonly statementTemplate?: string;
  readonly paper?: string;
  /** Leave out the cover page, e.g. when the booklet is one division of a bigger packet. */
  readonly cover?: boolean;
}

const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export function defaultLabel(index: number): string {
  if (index < LETTERS.length) return LETTERS[index] as string;
  const first = Math.floor(index / LETTERS.length) - 1;

  return `${LETTERS[first] as string}${LETTERS[index % LETTERS.length] as string}`;
}

export function booklet(
  problems: readonly BookletProblem[],
  contest: ContestMeta,
  options: BookletOptions = {},
): string {
  const template = options.template ?? "booklet.typ";
  const statementTemplate = options.statementTemplate ?? "statement.typ";
  const footerText = contest.footerText ?? contest.title;

  const labelled = problems.map((problem, index) => ({
    ...problem,
    label: problem.meta.label ?? contest.labels?.[index] ?? defaultLabel(index),
  }));

  const lines: string[] = [
    "// Generated by @moj/content. Edit the statements, not this file.",
    `#import ${typstEscapeString(template)}: booklet-doc, cover, problem-footer`,
    `#import ${typstEscapeString(statementTemplate)}: moj-markdown, problem-header`,
    "",
    `#show: booklet-doc.with(`,
    `  title: ${typstEscapeString(contest.title)},`,
    ...(options.paper ? [`  paper: ${typstEscapeString(options.paper)},`] : []),
    ")",
    "",
  ];

  if (options.cover !== false) {
    const entries = labelled
      .map((problem) => `    (${typstEscapeString(problem.label)}, ${typstEscapeString(problem.meta.name)}),`)
      .join("\n");

    lines.push(
      "#cover(",
      `  title: ${typstEscapeString(contest.title)},`,
      `  subtitle: ${typstOptional(contest.subtitle ?? null)},`,
      `  date: ${typstOptional(contest.date ?? null)},`,
      `  logo: ${typstOptional(contest.logo ?? null)},`,
      `  note: ${contest.note ? `moj-markdown(${typstEscapeString(contest.note)})` : "none"},`,
      "  entries: (",
      entries,
      "  ),",
      ")",
      "",
    );
  }

  for (const [index, problem] of labelled.entries()) {
    const meta: ProblemMeta = { ...problem.meta, label: problem.label };

    if (index > 0 || options.cover !== false) lines.push("#pagebreak()");
    lines.push(
      `#set page(footer: problem-footer(${typstEscapeString(footerText)}, ` +
        `${typstEscapeString(problem.label)}, ${typstEscapeString(problem.meta.name)}))`,
      "#problem-header(",
      ...statementArguments(meta).map((line) => `  ${line},`),
      ")",
      markdownToTypstBody(problem.statement, options),
      "",
    );
  }

  return `${lines.join("\n")}\n`;
}
