/**
 * `markdownToTypst` turns a statement plus its problem metadata into a compilable Typst
 * document that leans on `packages/content/typst/statement.typ`.
 */

import { typstEscapeString, typstOptional, typstStringArray } from "./escape.js";
import { type NormaliseOptions, normaliseForCmarker } from "./markdown.js";

export interface ProblemMeta {
  readonly name: string;
  readonly code: string;
  readonly points: number;
  /** Seconds, as DMOJ stores it. */
  readonly timeLimit: number;
  /** Kilobytes, as DMOJ stores it. */
  readonly memoryLimit: number;
  readonly pythonTimeLimit?: number | undefined;
  readonly authors: readonly string[];
  readonly inputType: string;
  readonly outputType: string;
  /** Contest letter, when the statement is part of a booklet. */
  readonly label?: string | undefined;
}

export interface TypstOptions extends NormaliseOptions {
  /** Import path of the template, relative to the compiled file. */
  readonly template?: string;
  /** Emit only the `#moj-markdown(...)` call, for embedding in a booklet. */
  readonly bodyOnly?: boolean;
  readonly paper?: string;
}

const GENERATED = "// Generated by @moj/content. Edit the statement, not this file.";

/** The `#moj-markdown("...")` call for one statement. */
export function markdownToTypstBody(source: string, options: TypstOptions = {}): string {
  const { markdown } = normaliseForCmarker(source, options);
  return `#moj-markdown(${typstEscapeString(markdown)})`;
}

export function statementArguments(meta: ProblemMeta): string[] {
  return [
    `name: ${typstEscapeString(meta.name)}`,
    ...(meta.label ? [`label: ${typstEscapeString(meta.label)}`] : []),
    `code: ${typstEscapeString(meta.code)}`,
    `points: ${typstOptional(meta.points)}`,
    `time-limit: ${typstOptional(meta.timeLimit)}`,
    `python-time-limit: ${typstOptional(meta.pythonTimeLimit ?? null)}`,
    `memory-limit: ${typstOptional(meta.memoryLimit)}`,
    `authors: ${typstStringArray(meta.authors ?? [])}`,
    `input-type: ${typstEscapeString(meta.inputType)}`,
    `output-type: ${typstEscapeString(meta.outputType)}`,
  ];
}

export function markdownToTypst(source: string, meta: ProblemMeta, options: TypstOptions = {}): string {
  const template = options.template ?? "statement.typ";
  const body = markdownToTypstBody(source, options);
  if (options.bodyOnly) return body;

  const args = statementArguments(meta);
  if (options.paper) args.push(`paper: ${typstEscapeString(options.paper)}`);

  return [
    GENERATED,
    `#import ${typstEscapeString(template)}: moj-markdown, statement-page`,
    "",
    "#statement-page(",
    ...args.map((line) => `  ${line},`),
    ")[",
    `  ${body}`,
    "]",
    "",
  ].join("\n");
}
