/**
 * Legacy DMOJ Bearer tokens and the API v2 envelope helpers.
 *
 * The tokens below were produced by DMOJ's own code path, in Python:
 *
 *   secret = bytes(range(32))
 *   token  = base64.urlsafe_b64encode(struct.pack('>I32s', 4919, secret))
 *   digest = hmac.new(b'django-insecure-moj-test-key', msg=secret,
 *                     digestmod='sha256').hexdigest()
 *
 * so a change to the decoder shows up as a mismatch against the real scheme
 * rather than against another copy of our own arithmetic.
 */

import { createHmac } from "node:crypto";
import { beforeAll, describe, expect, test } from "vitest";

// `@/auth/db` builds a pg Pool at import time, and `@/auth/server` needs a
// secret. Neither connects to anything in these tests.
process.env.DATABASE_URL ??= "postgresql://moj:moj@127.0.0.1:5433/moj_auth";
process.env.AUTH_SECRET ??= "test-secret-for-unit-tests-only-0123456789";

type ApiAuth = typeof import("./apiAuth");
let apiAuth: ApiAuth;

beforeAll(async () => {
  apiAuth = await import("./apiAuth");
});

const SECRET_KEY = "django-insecure-moj-test-key";

/** `generate_api_token` for user 4919 with `secret = bytes(range(32))`. */
const DMOJ_TOKEN = "AAATNwABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f";
const DMOJ_DIGEST = "e8ac60acafafb009ad576a6f0d7aef237a3aefbde3e7d29faf19797463023c25";

/** The same, with a secret that forces `-` and `_` into the base64url alphabet. */
const DMOJ_TOKEN_URLSAFE = "AAAAAfv_-__7__v_-__7__v_-__7__v_-__7__v_-__7__v_";
const DMOJ_DIGEST_URLSAFE = "cf6f3650bbefe5166c60025e31f9d5fdbdd9fe34397fdc9c6f575d39d8a55005";

describe("legacy token decoding", () => {
  test("a token generated by DMOJ decodes to its user id and digest", () => {
    const decoded = apiAuth.legacyTokenDigest(DMOJ_TOKEN, SECRET_KEY);
    expect(decoded).toEqual({ legacyUserId: 4919, digest: DMOJ_DIGEST });
  });

  test("base64url characters decode as base64url, not base64", () => {
    // 48 characters, but one short of 36 bytes because Python strips no padding
    // here: `-` and `_` must map to `+` and `/`.
    const token = `${DMOJ_TOKEN_URLSAFE}_`.slice(0, 48);
    const decoded = apiAuth.legacyTokenDigest(token, SECRET_KEY);
    expect(decoded?.legacyUserId).toBe(1);
    expect(decoded?.digest).toBe(DMOJ_DIGEST_URLSAFE);
  });

  test("the digest is HMAC-SHA256 of the secret under the secret key", () => {
    const secret = Buffer.from(Array.from({ length: 32 }, (_unused, i) => i));
    const expected = createHmac("sha256", SECRET_KEY).update(secret).digest("hex");
    expect(apiAuth.legacyTokenDigest(DMOJ_TOKEN, SECRET_KEY)?.digest).toBe(expected);
  });

  test("a different secret key gives a different digest", () => {
    const other = apiAuth.legacyTokenDigest(DMOJ_TOKEN, "some-other-key");
    expect(other?.legacyUserId).toBe(4919);
    expect(other?.digest).not.toBe(DMOJ_DIGEST);
  });

  test("our own builder round-trips through the decoder", () => {
    const secret = Buffer.from(Array.from({ length: 32 }, (_unused, i) => (i * 7) % 256));
    const token = apiAuth.buildLegacyToken(1234, secret);
    expect(token).toHaveLength(48);
    expect(apiAuth.BEARER_PATTERN.test(`Bearer ${token}`)).toBe(true);

    const decoded = apiAuth.legacyTokenDigest(token, SECRET_KEY);
    expect(decoded?.legacyUserId).toBe(1234);
    expect(decoded?.digest).toBe(createHmac("sha256", SECRET_KEY).update(secret).digest("hex"));
  });

  test("our builder reproduces DMOJ's token byte for byte", () => {
    const secret = Buffer.from(Array.from({ length: 32 }, (_unused, i) => i));
    expect(apiAuth.buildLegacyToken(4919, secret)).toBe(DMOJ_TOKEN);
  });

  test("a token that is not 36 bytes is rejected", () => {
    expect(apiAuth.legacyTokenDigest("c2hvcnQ", SECRET_KEY)).toBeNull();
  });
});

describe("the Bearer header", () => {
  test("DMOJ's pattern accepts both token families and nothing else", () => {
    expect(apiAuth.BEARER_PATTERN.test(`Bearer ${DMOJ_TOKEN}`)).toBe(true);
    // An api-key plugin key: 48 alphanumeric characters.
    expect(apiAuth.BEARER_PATTERN.test(`Bearer ${"a1B2".repeat(12)}`)).toBe(true);

    expect(apiAuth.BEARER_PATTERN.test("Bearer short")).toBe(false);
    expect(apiAuth.BEARER_PATTERN.test(`Token ${DMOJ_TOKEN}`)).toBe(false);
    expect(apiAuth.BEARER_PATTERN.test(`Bearer ${DMOJ_TOKEN}x`)).toBe(false);
    expect(apiAuth.BEARER_PATTERN.test(`Bearer ${"!".repeat(48)}`)).toBe(false);
  });

  test("no header at all is anonymous, a bad one is malformed", async () => {
    expect(await apiAuth.authenticateRequest(new Request("http://x/api/v2/users"))).toEqual({
      status: "anonymous",
    });
    expect(
      await apiAuth.authenticateRequest(
        new Request("http://x/api/v2/users", { headers: { authorization: "Basic abc" } }),
      ),
    ).toEqual({ status: "malformed" });
  });

  test("safeEqual compares without leaking length through an exception", () => {
    expect(apiAuth.safeEqual("abc", "abc")).toBe(true);
    expect(apiAuth.safeEqual("abc", "abd")).toBe(false);
    expect(apiAuth.safeEqual("abc", "abcd")).toBe(false);
  });
});

describe("the API v2 envelope", () => {
  const request = new Request("http://x/api/v2/users");

  test("a data response carries DMOJ's three header fields", async () => {
    const response = apiAuth.apiJson(request, { objects: [] });
    expect(response.status).toBe(200);
    const body = (await response.json()) as Record<string, unknown>;
    expect(body.api_version).toBe("2.0");
    expect(body.method).toBe("get");
    expect(typeof body.fetched).toBe("string");
    expect(new Date(body.fetched as string).toISOString()).toBe(body.fetched);
    expect(body.data).toEqual({ objects: [] });
    expect(body.error).toBeUndefined();
  });

  test("an error response carries the code and the message, and no data", async () => {
    const response = apiAuth.apiError(request, 404, "page/object not found");
    expect(response.status).toBe(404);
    const body = (await response.json()) as Record<string, unknown>;
    expect(body.error).toEqual({ code: 404, message: "page/object not found" });
    expect(body.data).toBeUndefined();
  });

  test("a ConvexError maps onto DMOJ's error table", async () => {
    const cases: [string, number, string][] = [
      ["NOT_FOUND", 404, "page/object not found"],
      ["FORBIDDEN", 403, "permission denied"],
      ["UNAUTHENTICATED", 403, "login required"],
      ["INVALID", 400, "invalid filter value type"],
    ];
    for (const [code, status, message] of cases) {
      const response = apiAuth.errorResponse(request, { data: { code, message: "whatever" } });
      expect(response.status).toBe(status);
      const body = (await response.json()) as { error: { code: number; message: string } };
      expect(body.error).toEqual({ code: status, message });
    }
  });

  test("a login-required forbidden keeps DMOJ's wording", async () => {
    const response = apiAuth.errorResponse(request, {
      data: { code: "FORBIDDEN", message: "login required" },
    });
    const body = (await response.json()) as { error: { message: string } };
    expect(body.error.message).toBe("login required");
  });

  test("an error that is not a ConvexError is rethrown", () => {
    expect(() => apiAuth.errorResponse(request, new Error("boom"))).toThrow("boom");
  });
});

describe("query-string filters", () => {
  const url = (query: string) => new URL(`http://x/api/v2/problems${query}`);

  test("a basic filter takes one value, a list filter takes them all", () => {
    expect(apiAuth.basicFilter(url("?code=a&code=b"), "code")).toBe("a");
    expect(apiAuth.listFilter(url("?code=a&code=b"), "code")).toEqual(["a", "b"]);
    expect(apiAuth.listFilter(url("?"), "code")).toBeUndefined();
  });

  test("booleans follow Django's spelling and reject anything else", () => {
    expect(apiAuth.booleanFilter(url("?partial=true"), "partial")).toBe(true);
    expect(apiAuth.booleanFilter(url("?partial=1"), "partial")).toBe(true);
    expect(apiAuth.booleanFilter(url("?partial=False"), "partial")).toBe(false);
    expect(apiAuth.booleanFilter(url("?partial=0"), "partial")).toBe(false);
    expect(apiAuth.booleanFilter(url("?"), "partial")).toBeUndefined();
    expect(() => apiAuth.booleanFilter(url("?partial=maybe"), "partial")).toThrow(TypeError);
  });

  test("numbers must be integers", () => {
    expect(apiAuth.numberFilter(url("?virtual=3"), "virtual")).toBe(3);
    expect(apiAuth.numberFilter(url("?virtual=-1"), "virtual")).toBe(-1);
    expect(() => apiAuth.numberFilter(url("?virtual=1.5"), "virtual")).toThrow(TypeError);
  });

  test("the page must be a positive integer", () => {
    expect(apiAuth.pageFilter(url("?"))).toBe(1);
    expect(apiAuth.pageFilter(url("?page=4"))).toBe(4);
    expect(() => apiAuth.pageFilter(url("?page=0"))).toThrow(RangeError);
    expect(() => apiAuth.pageFilter(url("?page=last"))).toThrow(RangeError);
  });

  test("withFilters turns a bad filter into the error envelope", async () => {
    const request = new Request("http://x/api/v2/problems?partial=maybe");
    const response = await apiAuth.withFilters(request, async (target) => {
      apiAuth.booleanFilter(target, "partial");
      return new Response("unreachable");
    });
    expect(response.status).toBe(400);
    const body = (await response.json()) as { error: { message: string } };
    expect(body.error.message).toBe("invalid filter value type");
  });

  test("withFilters turns a bad page into a not-found envelope", async () => {
    const request = new Request("http://x/api/v2/problems?page=0");
    const response = await apiAuth.withFilters(request, async (target) => {
      apiAuth.pageFilter(target);
      return new Response("unreachable");
    });
    expect(response.status).toBe(404);
    const body = (await response.json()) as { error: { message: string } };
    expect(body.error.message).toBe("page/object not found");
  });
});
